### ISSUE TITLE
No code completion for DerelicGL3/DerelicGLFW3

### ISSUE THREAD

**Issue by RUSshy** [LaurentTreguier/dls#4]
Hi

I'm using these dependencies and i can't have code completion for both

It is not that much annoying since i don't have to call the functions that often, but i think it could be nice if it was supported

https://github.com/DerelictOrg/DerelictGL3
https://github.com/DerelictOrg/DerelictGLFW3

**Comment by LaurentTreguier** [comment]
It looks like DCD somehow has problems with `import derelict.opengl3;` but not `import derelict.opengl3.gl` for example. Importing `derelict.opengl3` uses a `package.d` file and I'm guessing this could be posing a problem, although I've had no problem with `package.d` files before.
What kind of import statements are you using ?

**Comment by RUSshy** [comment]
I am using:

```
import derelict.opengl3.gl3;
import derelict.glfw3.glfw3;
```

I tried ``import derelict.opengl3.gl`` but it still doesn't work

**Comment by LaurentTreguier** [comment]
It works on my machine... Is it a new project ? (completions for libs use `dub.selections.json` for DCD to import the correct versions, so if it hasn't been generated yet you'll have no completion)

**Comment by LaurentTreguier** [comment]
There could be a subproject with its own selections file, so that's why I'm monitoring everything. But I guess I could dismiss stuff that's below the .dub folders.

**Comment by RUSshy** [comment]
I just restarted vscode and it stopped to give completion for both packages
(i'm on windows)

**Comment by RUSshy** [comment]
It give completion if:

i delete the .dub/ folder and dub.selection.json file, and then build the project

but if i restart vscode then it doesn't give completion for both package anymore

**Comment by LaurentTreguier** [comment]
This is weird. I can't reproduce this, do you have any reduced example of this behavior ? (meanwhile, c270d14080d77c4fb8db0cd5f073b8e7c52e604b will take care of ignoring `.dub/diub.json` from now on)

**Comment by RUSshy** [comment]
I tried with the latest commit it still doesn't work :/

Here is the project, i removed all other subpackages

[somethingd.zip](https://github.com/LaurentTreguier/dls/files/2129286/somethingd.zip)

**Comment by RUSshy** [comment]
I tried with sublime text and same issue, code completion works fine, but not for both packages

**Comment by LaurentTreguier** [comment]
It should be alright now (do re-open if it's not the case)

**Comment by RUSshy** [comment]
It fixed it!!! thanks a lot you are awesome!

**Comment by LaurentTreguier** [comment]
Just a quick question : did you just update DLS using the update popup ? I'm not getting it myself and I fear I've somehow broken the update system (again)
