### ISSUE TITLE
Crash with bigger projects

### ISSUE THREAD

**Issue by LaurentTreguier** [LaurentTreguier/dls#5]
See Szymon Jankowski's review of vscode-dls (https://marketplace.visualstudio.com/items?itemName=LaurentTreguier.vscode-dls#review-details)

**Comment by LaurentTreguier** [comment]
It indeed crashes with https://github.com/szymski/Rayman2Lib.

**Comment by LaurentTreguier** [comment]
Could be fixed by 7088591fdc5ed6e11b06dc5cc9f0c28e13a47448

**Comment by szymski** [comment]
It's not crashing anymore 😄
