### ISSUE TITLE
dls with LanguageClient-neovim

### ISSUE THREAD

**Issue by viniarck** [LaurentTreguier/dls#6]
@LaurentTreguier,

I'm trying to use dls 0.8.0 with this LSP server plugin for neovim: https://github.com/autozimu/LanguageClient-neovim. However, I keep getting some errors, so I'm wondering if there's any argument missing to initialize dls or if dls is not compatible with LanguageClient-neovim.

Here's a minimal config, the `'d': ['dls']` line, associates any d source file with this `dls` command as the LSP client:

```
set hidden
" Automatically start language servers.
let g:LanguageClient_autoStart = 1
let g:LanguageClient_diagnosticsEnable = 0
let g:LanguageClient_serverCommands = {
    \ 'd': ['dls'],
    \ }

let g:LanguageClient_loggingLevel = 'DEBUG'
let g:LanguageClient_loggingFile = "/tmp/LaguageClient.log"
```

And, in the logs, there's this `"OSerror 20 Not a directory"` error whenever I try to use the LSP client functions.

```
12:40:07 INFO reader-main src/vim.rs:389 <= None {"id": 13, "jsonrpc": "2.0", "result": 1}
12:40:07 ERROR main src/vim.rs:57 Error handling message: Not a directory (os error 20)

Message: {"jsonrpc":"2.0","method":"languageClient/startServer","params":{"buftype":"","cmdargs":[],
"filename":"/home/viniarck/repos/dlang/helloworld/hello.d","languageId":"d"},"id":1}

Error: Os { code: 20, kind: Other, message: "Not a directory" }
12:40:07 INFO main src/vim.rs:90 => None {"jsonrpc":"2.0","error":{"code":-32603,"message":"Not a di
rectory (os error 20)"},"id":1}
```

I'm positive my current cwd in vim is the project directory of where the d source files are. Do you have idea what might be the issue? Should I set any additional arguments to start dls? I appreciate any tips to run dls with neovim.

Thanks!

**Comment by LaurentTreguier** [comment]
> I'm wondering if there's any argument missing to initialize dls

Nope, just launching the executable is enough. This is how I launch it with VSCode and Atom.

> or if dls is not compatible with LanguageClient-neovim

In theory, since it's using the LSP, it shouldn't pose any problem. However, obviously things are always quirky in practice no matter what the theory is, so it's no big surprise if things don't work out the first time around (for example I've had to fix it to work with Sublime text, and I think I still have autocompletion problems with Intellij Idea)
I've never tried any vim or vim-like LSP client for now, but I'll try to have a look and see what's wrong.

The `languageClient/startServer` is not part of the LSP spec, so in its current state DLS will inevitably send back an error with the code `-32601` (`MethodNotFound`). I'll start by looking at their docs.

**Comment by LaurentTreguier** [comment]
Out of curiosity, why is the starting command just `dls` and not something like `~/.dub/packages/.bin/dls` ?
Also, if you have a full log file of every request, maybe that could give some clue about what's going on

**Comment by daehlith** [comment]
Not sure if this is very useful for you @viniarck, but I've got `dls` to work with https://github.com/natebosch/vim-lsc out of the box, (MacOS Sierra, Vim8 installed via homebrew). All I did was to symlink `dls` into my `$PATH` and configure it accordingly in my `.vimrc`:
```vim
let g:lsc_server_command={'d': 'dls'}
let g:lsc_auto_map=v:true
```

**Comment by viniarck** [comment]
@LaurentTreguier, 

 Sure. I'm attaching the full log file, including a minimal `init.vim` to reproduce the issue on neovim. 

[dls_neovimclient.txt](https://github.com/LaurentTreguier/dls/files/2267789/dls_neovimclient.txt)
[min.vim.txt](https://github.com/LaurentTreguier/dls/files/2267793/min.vim.txt)

Regarding, the `dls` instead of the full path in the configuration, actually I have `~/.dub/packages/.bin/` in my PATH: 

```
❯ which dls
/home/viniarck/.dub/packages/.bin/dls
```

Thanks for this prompt reply. Let me know if you need further information or if I should also contact the author of LanguageClient-neovim.

**Comment by viniarck** [comment]
@daehlith, I'd rather stick with LanguageClient-neovim because it integrate seamlessly with [deoplete](https://github.com/Shougo/deoplete.nvim), which is a completion manager that I rely on to manage all completion sources, just so I can have an ubiquitous experience and more granular control to select the completion candidates (matcher, ranks and so on). Thanks for the information, appreciate that, depending on how this issue turns out I'll fallckback to vim-lsc.

**Comment by LaurentTreguier** [comment]
I do get a few errors:
```sh
cat /tmp/LanguageClient.log | grep -i error                                                                                 mar. 07 août 2018 22:47:58 CEST
22:54:09 INFO main src/vim.rs:90 => None {"jsonrpc":"2.0","method":"execute","params":["sign define LanguageClientWarning text=⚠ texthl=ALEWarningSign","sign define LanguageClientInformation text=ℹ texthl=ALEInfoSign","sign define LanguageClientHint text=➤ texthl=ALEInfoSign","sign define LanguageClientError text=✖ texthl=ALEErrorSign"],"id":11}
22:54:09 WARN main src/languageclient.rs:763 Failed to get initializationOptions: No such file or directory (os error 2)
22:54:10 WARN main src/languageclient.rs:2762 Failed to get workspace settings: No such file or directory (os error 2)
22:54:10 INFO main src/vim.rs:90 => None {"jsonrpc":"2.0","method":"nvim_buf_add_highlight","params":[0,0,"Error",1,1,1],"id":19}
22:54:10 ERROR main src/vim.rs:57 Error handling message: entity not found
Error: Io(Os { code: 2, kind: NotFound, message: "No such file or directory" })
22:54:10 INFO main src/vim.rs:90 => Some("d") {"jsonrpc":"2.0","error":{"code":-32603,"message":"entity not found"},"id":"dls-aa0f565d-81ca-4c6e-9da9-273581991bdd"}
```

But they seem harmless enough, simply no server settings and such. I do get a message in neovim indicating the server is launched, and I can jump to a declaration for example.
I'm trying this on Ubuntu 18.04, I installed LanguageClient-neovim with [vim-plug](https://github.com/junegunn/vim-plug) since it was shown in the quick start section.
Are you on a Linux or on macOS ?

**Comment by viniarck** [comment]
I'm running Linux. I just figured out. God dammit. It turns out it was the full binary path like you initially pointed out to me @LaurentTreguier. I still don't understand why it doesn't find dls in the path tough, it has to be something with LanguageClient-neovim:

```
❯ sh
sh-4.4$ which dls
/home/viniarck/.dub/packages/.bin/dls
sh-4.4$ exit
exit

❯ bash
[viniarck@volos LanguageClient-neovim]$ which dls
/home/viniarck/.dub/packages/.bin/dls
[viniarck@volos LanguageClient-neovim]$ exit
exit

```

Here's the final configuration setup on the server, if anyone stumbles upon this again.

```
let g:LanguageClient_serverCommands = {
    \ 'd': ['~/.dub/packages/.bin/dls'],
    \ }
```

Sorry about that! Thanks for your contribution and support.

**Comment by LaurentTreguier** [comment]
No problem!
